// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLv94Cw7-Fv8_QTTbnl_TXEL4e-Xm638',
    appId: '1:251307527873:web:9bd7168a7ad0eb3bb64e40',
    messagingSenderId: '251307527873',
    projectId: 'spotify-clone2024',
    authDomain: 'spotify-clone2024.firebaseapp.com',
    storageBucket: 'spotify-clone2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwktpy2LDRVO7N-3FTqTCTGcLeRARLIOU',
    appId: '1:251307527873:android:7b4b7dfdd393ee5cb64e40',
    messagingSenderId: '251307527873',
    projectId: 'spotify-clone2024',
    storageBucket: 'spotify-clone2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgNcMib4T3Y2aa-ZGP8M_8CxRmbHixcPI',
    appId: '1:251307527873:ios:33a5bdd29f0db304b64e40',
    messagingSenderId: '251307527873',
    projectId: 'spotify-clone2024',
    storageBucket: 'spotify-clone2024.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgNcMib4T3Y2aa-ZGP8M_8CxRmbHixcPI',
    appId: '1:251307527873:ios:33a5bdd29f0db304b64e40',
    messagingSenderId: '251307527873',
    projectId: 'spotify-clone2024',
    storageBucket: 'spotify-clone2024.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSLv94Cw7-Fv8_QTTbnl_TXEL4e-Xm638',
    appId: '1:251307527873:web:2366e2eb69897be5b64e40',
    messagingSenderId: '251307527873',
    projectId: 'spotify-clone2024',
    authDomain: 'spotify-clone2024.firebaseapp.com',
    storageBucket: 'spotify-clone2024.firebasestorage.app',
  );

}